### ISSUE TITLE
Format error when starting docker container

### ISSUE THREAD

**Issue by tazomatalax** [arankwende/ipmi-mqtt#2]
Getting this error on starting docker container:

`ipmi-mqtt    | exec /bin/sh: exec format error`

I also dont have a user or password for my MQTT broker, would this be an issue?
here is my config 

```
MQTT:
    MQTT_ip: 192.168.1.xxx
    MQTT_ID: "ipmi-mqtt-server"
    MQTT_USER: ''
    MQTT_PW: ''
    HA_BINARY: 'homeassistant/binary_sensor' # MQTT topics for home assistant to automatically detect devices
    HA_SENSOR: 'homeassistant/sensor'
    HA_SWITCH: 'homeassistant/switch'
    TIME_PERIOD: 300 # Time to try to get new sensor values. Set to 0 for one time execution.

TOPICS:
    POWER: 'server_power_state' #This is to get the server's ON OFF state, if you don't want it just leave an empty string
    SDR_TYPES: #THESE ARE JUST EXAMPLES OF NAMES FOR THE SENSORS, ITS A DICTIONARY SO THE first part (before :) can be whatever you want, just ensure it matches the value in SDR TYPE for this description.
        1: 'server_cpu1_temp' 
        2: 'server_system_temp'
        3: 'server_cpu1_fan'
        4: 'server_bmc_voltage'
        5: 'server_cpu2_temp'  
        6: 'server_cpu2_fan'
SERVERS:
      - IPMI_NODENAME: Fred
        BRAND: SUPERMICRO #THIS IS A SUPERMICRO EXAMPLE
        IPMI_IP: 192.168.1.xxx
        IPMI_USER: 'username'
        IPMI_PASSWORD: 'asupersecretpassword'
        SDRS: # YOU CAN ADD ALL THE SDRS YOU WAN
            - SDR_TYPE: 1
              VALUE: 3.1
              SDR_CLASS: temperature
            - SDR_TYPE: 5
              VALUE: 3.2
              SDR_CLASS: temperature
            - SDR_TYPE: 2
              VALUE: 7.1
              SDR_CLASS: temperature
            - SDR_TYPE: 3
              VALUE: 29.2
              SDR_CLASS: fan
            - SDR_TYPE: 6
              VALUE: 29.6
              SDR_CLASS: fan
```
