### ISSUE TITLE
IPMI on / off via MQTT

### ISSUE THREAD

**Issue by jerzyks** [arankwende/ipmi-mqtt#4]
Did You find the way to send command?

**Comment by arankwende** [comment]
Yes! You can look at the code on the on_message callback function, if the message is "on", then it executes the IPMI Power On command, if it's off, the Power Off command, this always listening to an MQTT topic for the switch (which Home assistant recognizes).

**Comment by jerzyks** [comment]
Well - I'm impressed with your work, but I read it a few times and I'm sure I'm too stupid for all this, but I promise I will try to install it anyway :-) I could use some step-by-step tutorial on your community.home- assistant.io

Thanks for your work and reply!

**Comment by arankwende** [comment]
Well, I don't mind helping you installing and configuring it if you need to. The main things are:
1. Setting up the yaml config file correctly
2. installing the daemon
With that, it should work. Where are you stuck?

**Comment by jerzyks** [comment]
Ok, thank you very much for your willingness to help, I chose the docker version, spent a bit on it and what I have figured out:
- I created a docker by Your command: 
`docker run -p 1886:1886/tcp -v /mnt/c/ipmi-mqtt/config:/ipmi-mqtt/config --name ipmi-mqtt arankwende/ipmi-mqtt`
- I created in /mnt/c/ipmi-mqtt/config/config.yml:
MQTT:
   MQTT_ip: 192.168.X.X
   MQTT_ID: "ipmi-mqtt-server"
   MQTT_USER: 'mqtt'
   MQTT_PW: 'mqtt'
   HA_BINARY: 'homeassistant/binary_sensor' # MQTT topics for home assistant to automatically detect devices
   HA_SENSOR: 'homeassistant/sensor'
   HA_SWITCH: 'homeassistant/switch'
   TIME_PERIOD: 300 # Time to try to get new sensor values. Set to 0 for one time execution.

TOPICS:
    POWER: 'server_power_state'  
    SDR_TYPES:  
        1: 'CPU Temp' 

SERVERS:
      - IPMI_NODENAME: NAS
        BRAND: SUPERMICRO 
        IPMI_IP: 192.168.Y.Y
        IPMI_USER: 'YYYY'
        IPMI_PASSWORD: 'ZZZZ'
        SDRS: 
            - SDR_TYPE: 1
              SDR_CLASS: temperature
              VALUE: 01h
 
- manually start container ipmi-mqtt and container brings error:
`Traceback (most recent call last):
  File "/ipmi-mqtt/ipmi-mqtt.py", line 570, in <module>
    main ()
  File "/ipmi-mqtt/ipmi-mqtt.py", line 441, in main
    topic_dict, power_topic, switch_topic, sdr_topic_types, sdr_count = get_topics (config)
  File "/ipmi-mqtt/ipmi-mqtt.py", line 181, in get_topics
    return topic_dict, power_topic, switch_topic, sdr_topic_types, sdr_count
UnboundLocalError: local variable 'switch_topic' referenced before assignment`
- a log information
`[2022-11-04 19: 57: 38,466] INFO [root.load_config: 23] Opening the following file: /ipmi-mqtt/config/config.yaml`
`[2022-11-04 19: 57: 38,472] INFO [root.main: 428] You have 1 servers.`
`[2022-11-04 19: 57: 38,498] WARNING [root.get_topics: 169] There is no switch topic in your YAML file.`
`[2022-11-04 19: 57: 38,499] INFO [root.get_topics: 180] You have 1 SDRs in your YAML file.`
- Where did I go wrong?
- What triggers the query to the container docker? HA?

**Comment by arankwende** [comment]
Clearly, the problem is when reading the switch topic as the variable is
not assign, ie. It hasn't created it.

**Comment by arankwende** [comment]
Ok, I see the problem, I'll fix it Sunday, there seems to be a wrong variable switch_topic instead of ha_switch_topic

**Comment by jerzyks** [comment]
OK, just let me know when You figure it, i'll test it, thank You

**Comment by arankwende** [comment]
Ok, so looking back at it, there seems to not be any switch topic on your yaml file.
On your Topics part, there should be:
TOPICS:
    POWER: 'server_power_state'
    SWITCH: 'server_switch'

Try adding that SWITCH:'server_switch' line and try again. That should do it.

**Comment by jerzyks** [comment]
Ok, I've been sitting on it for a few days now and I had a few problems with the docker itself, the mqtt broker and it's already pretty good. Your application already works to power on and off and update the power status. Unfortunately, it does not show the CPU temperature as an entity in HA. The MQTT Explorer shows that in mqtt this temperature is passed to the HA but it is not there anymore. 
![image](https://user-images.githubusercontent.com/18427637/201225578-d4b478ee-de6c-4f23-9ba8-f679f8285aaa.png)

I downloaded config_entry-mqtt json and there is no sensor section from this device at all. I wonder if this section - sensor (?) Is compatible with HA?

![image](https://user-images.githubusercontent.com/18427637/201225727-308e917c-72dc-4638-a5db-f88bcb220235.png)

**Comment by arankwende** [comment]
Could you paste here the whole config message on the sensor topic from MQTT Explorer? I suspect something is amiss there.

**Comment by jerzyks** [comment]
ok, sure:

```
MQTT:
    MQTT_ip: 192.168.1.183
    MQTT_ID: "ipmi-mqtt-supermicro"
    MQTT_USER: "zzz"
    MQTT_PW: "xxx"
    HA_BINARY: "homeassistant/binary_sensor" # MQTT topics for home assistant to automatically detect devices
    HA_SENSOR: "homeassistant/sensor"
    HA_SWITCH: "homeassistant/switch"
    TIME_PERIOD: 10 # Time to try to get new sensor values. Set to 0 for one time execution.

TOPICS:
    POWER: "server_power_state" #This is to get the server"s ON OFF state, if you don"t want it just leave an empty string
    SWITCH: "server_switch" 
    SDR_TYPES: #THESE ARE JUST EXAMPLES OF NAMES FOR THE SENSORS, ITS A DICTIONARY SO THE first part (before :) can be whatever you want, just ensure it matches the value in SDR TYPE for this description.
        1: "CPU Temp" 

SERVERS:
      - IPMI_NODENAME: TRueNASmqtt
        BRAND: SUPERMICRO #THIS IS A SUPERMICRO EXAMPLE
        IPMI_IP: 192.168.x.yyy
        IPMI_USER: "ADMIN"
        IPMI_PASSWORD: "12345678"
        SDRS: # YOU CAN ADD ALL THE SDRS YOU WAN
            - SDR_TYPE: 1
              SDR_CLASS: temperature
              VALUE: 3.1 
```
piece of log looks like this:
```
[2022-11-13 21:51:23,433] INFO [root.load_config:23] Opening the following file: /ipmi-mqtt/config/config.yaml
[2022-11-13 21:51:23,439] INFO [root.main:428] You have 1 servers.
[2022-11-13 21:51:23,470] INFO [root.get_topics:180] You have 1 SDRs in your YAML file.
[2022-11-13 21:51:23,474] INFO [root.main:454] Connecting to MQTT Broker: waiting in loop until until the connection is established.
[2022-11-13 21:51:24,475] INFO [root.main:454] Connecting to MQTT Broker: waiting in loop until until the connection is established.
[2022-11-13 21:51:24,488] INFO [root.on_subscribe:104] The server has acknowledged your subscription requested on mid 1 with qos (0,)
[2022-11-13 21:51:25,477] INFO [root.main:456] Returning to the main loop, succesfully connected to the broker on 192.168.1.183, with id ipmi-mqtt-supermicro and user tasmota
[2022-11-13 21:51:25,478] INFO [root.main:466] Initialization complete.
[2022-11-13 21:51:25,478] INFO [root.switch_subscribe:100] You are now subscribed to homeassistant/switch/31303134-534d-ec3c-efb1-3aa600000000_server_switch/set.
[2022-11-13 21:51:25,495] INFO [root.on_subscribe:104] The server has acknowledged your subscription requested on mid 5 with qos (2,)
[2022-11-13 21:51:25,698] INFO [root.main:502] Collection complete, will wait 10 seconds to start again
[2022-11-13 21:51:35,920] INFO [root.main:502] Collection complete, will wait 10 seconds to start again
```
thank you very much for helping me!
